### ISSUE TITLE
Demo link does not work

### ISSUE THREAD

**Issue by jithinbp** [bevacqua/ponymark#1]
Hi,
The [demo on codepen](https://codepen.io/bevacqua/full/AlFhD) linked in the README just shows an unresponsive area on codepen running on chrome Version 60.0.3112.90 (Official Build) (64-bit), Ubuntu. Could you please take a look? The image upload enhancement in Ponymark is quite useful, and I would like to use it.
many thanks
![ponymark](https://user-images.githubusercontent.com/6078658/30196074-925d15f2-947b-11e7-9c8f-84bb25e7af18.png)

**Comment by bevacqua** [comment]
Please consider `woofmark` instead.

**Comment by bevacqua** [comment]
https://github.com/bevacqua/woofmark

It's sort of the evolution of this project, which I've mostly discontinued. If you only turn on the Markdown aspect, it's very similar to this one.

**Comment by jithinbp** [comment]
Thanks a lot. the [demo](https://bevacqua.github.io/woofmark/) looks great.
I've been hunting for a github comments style markdown editor with a preview tab and image upload ability.
I'll try to explore and figure out how to enable pure markdown window in woofmark, and make the preview in a separate tab.

There exists a large collection of scientific simulation code snippets called [pycode-browser](https://github.com/sposh-science/pycode-browser/). I'm making a [webapp for it with EmberJS](http://eyes-online.surge.sh/#/pycode-browser) and would like to encourage community driven contributions towards documentation. hence the need for woofmark.

thanks a lot. :)
